---
title: 'Keep rollin'': guiding principles for a continuous knowledge accumulation
  initiative  (or “rolling Metaketa”)'
author: "Macartan Humphreys, Alexandra Scacco & Julio S. Solís Arce"
date: "8/21/2020"
bibliography: [bib_white_paper.bib]
link-citations: true
abstract: "Efforts to solve problems endemic to experimental research in the social sciences have been undertaken in the last few years. One prominent example is EGAP’s Metaketa initiative. Metaketas have the limitations of being onerous, driven by policy priorities and “artificial” when compared to the usual proceedings of science. We lay out the guiding principles for a continuous knowledge accumulation initiative or “rolling Metaketa”. Studies following this novel approach are 1) theory-driven; 2) non-simultaneous; and 3) semi-autonomous. The spirit is that a scientific committee launches a “challenge” that aims to fill a theoretical or empirical gap of relevance to a given field. This is done by 1) declaring explicitly an underlying theory and 2) setting up a rolling meta-analysis that maps empirical research to the theory. In this way, anyone can transparently recognize the state of a theory and openly scrutinize the committee’s assessment. Anyone is then free to adhere to this research program and address the challenge. If their project follows the theory, the only admissibility criteria, they are added to the rolling meta-analysis. Other features could be added to these guiding principles, including temporality and coordination. We contend that this approach follows closely the actual process of scientific research and knowledge accumulation."
output: word_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Metaketa Initiative

From some years now, social scientists began to acknowledge some problematic trends across their scientific endeavours including study sparsity, study heterogeneity, selective reporting and private data. To these problems of scientific practice, we must add those endemic to empirical research, especially randomized controlled trials (RCTs), including the limited external validity. Taken together, these problems limit the possible learning to be drawn from research in order to inform policy and theory [@dunning_information_2019, 16-25].

Amongst the innovative initiatives to address these problems, and propose a path towards transparent, replicable and cumulative learning, EGAP’s Metaketa approach stands at the forefront. Metaketa essentially consists in the coordinated implementation of field experiments with a common research question and treatment arm carried out in multiple sites. After the individual interventions are finished, a meta-analysis with the overall findings is done with ease due to the harmonization in measurements of inputs, outcomes and controls. The Metaketa initiative also keeps the highest standard in research transparency and reproducibility, through open data and code, third-party data analysis and pre-registration of designs and analysis plans [@dunning_information_2019, 25-30].

With all the great advances that Metaketa presents to push for knowledge accumulation and to tackle external validity it is also comes with several limitations, as the conceivers of the initiative themselves recognise [@dunning_information_2019, 31].  Some of these are related to financing. Metaketas are onerous and can only be funded with sizable donations. These strictly financial limitations, extend to substantive terms when we consider that only those topics that are relevant for donors or policy makers receive grants to be carried on. This potentially excludes a wide number of subjects relevant to the scientific community which are not necessarily aligned with policy priorities or funders interests. 

Relatedly, Metaketas are, to some extent, artificial when compared to the “natural” proceeding of science and knowledge accumulation. For instance, most of the scientific efforts are not centrally coordinated. They also have lengthy timeframes, sometimes spanning over decades or a life time. They are also done on a much smaller scale, within the lab or even a single country. Paradoxically, it is as a response to this state of things that Metaketa arose in the first place!

Finally, and most importantly, a project as ambitious as Metaketa might give the wrong impression of a definite account of a long-standing puzzle. How could a new single study with contradictory findings to those in a Metaketa be added to the corpus of knowledge? Is it worth pursuing similar interventions that are not done within this framework? 

## A post-Metaketa approach

Logically, the conceivers of Metaketa were well aware of these problems and pointed towards a way forward. For example, results from a Metaketa could be regarded as the null hypothesis that further studies could reject. Moreover, elements from the design, especially the common treatment arm, could be freely borrowed and implemented in new interventions. Then, a large number of new studies could be added in a new metanalysis and feedback the results of a given research agenda [@dunning_information_2019, 413]. In this way, Metaketa is just one piece of evidence with no authoritative pretensions.
Seeing the results of Metaketa in this light, as one piece of the puzzle rather than the last piece, highlights the core of the initiative, which is lost in the tremendous effort of gathering financial resources, coordinating teams and implementing across multiple sites. If we remove these organizational details we are left with three core elements: 1) a common theory; 2) a common strategy in terms of design; and 3) an aggregation process. By taking only these elements we could conceive a “more decentralized version of the Metaketa model, in which a core team lays out strategies in advance and criteria for inclusion […] and future research teams opt in when undertaking a relevant project” [@dunning_information_2019, 413]. We call this a “rolling” Metaketa. 

## Rolling Metaketa

An initiative like the one we envision has three core guiding principles, one substantive and two organizational. 

First of all, it is theory-driven. This means that the main motivation should be concerned to answer core questions in the social sciences, rather than taking the form of some impact evaluation. 

The second principle is non-simultaneity. By this we mean that we do not require studies to occur in a given time frame. Removing time constraints will let studies involved in this type initiative to learn from each other, perhaps in a staggered way. 

Finally, the third principle is that a rolling Metaketa is its semi-autonomy. While the organization might need to be centralized in a research institution or university, participation is voluntary and non-incentivized. Strategies should be devised to implement the initiative with as few middlepersons as possible. Coordination meetings and lengthy discussion should only occur at the set-up stage, with the rest of the process happening in an open and dynamic manner. 

### A theory
The core element of a rolling Metaketa is a theory. A theory lays out the relevant variables and the causal relationship between them that explain a given phenomenon. While oftentimes such theories as posited as a narrative, they could be translated into a causal diagram. Causal diagrams “are simply dot-and-arrow pictures that summarize our existing scientific knowledge. The dots represent know quantities of interest, called ‘variables,’ and the arrows represent known or suspected causal relationships between those variables” [@pearl_book_2018, 7].

A causal diagram is a depiction of a causal model as posited by a theory (Humphreys and Jacobs, forthcoming). These causal models can be constructed to be detailed and specific or rather general. The main advantage of representing a theory this way is that causal links are transparently shown, interactions between variables can be fully flesh out, functional relations among variables can be specified with flexibility, and uncertainty and confounders can be rightly represented inside the model (Pearl; Humphreys & Jacobs, forthcoming). 

### An aggregation process
### A menu of strategies

### References
